// Licensed to the Apache Software Foundation (ASF) under one
// or more contributor license agreements.  See the NOTICE file
// distributed with this work for additional information
// regarding copyright ownership.  The ASF licenses this file
// to you under the Apache License, Version 2.0 (the
// "License"); you may not use this file except in compliance
// with the License.  You may obtain a copy of the License at
//
//   http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing,
// software distributed under the License is distributed on an
// "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
// KIND, either express or implied.  See the License for the
// specific language governing permissions and limitations
// under the License.

function positiveInteger (value) {
  const parsed = Number(value)
  return Number.isInteger(parsed) && parsed > 0 ? parsed : undefined
}

export function resolveTargetComputeSizingValue (resolvedValue, existingValue, preserveExisting) {
  const resolved = positiveInteger(resolvedValue)
  if (resolved) return resolved
  return preserveExisting ? positiveInteger(existingValue) : undefined
}

export function buildChangedPlanPayload (current = {}, baseline = {}) {
  return Object.keys(current).reduce((changed, key) => {
    if (JSON.stringify(current[key]) !== JSON.stringify(baseline[key])) {
      changed[key] = current[key]
    }
    return changed
  }, {})
}

export function updateAutoGeneratedDiskNames (rows = [], oldTargetVmName, newTargetVmName) {
  const oldPrefix = oldTargetVmName || 'dr-target'
  const newPrefix = newTargetVmName || 'dr-target'
  return rows.map((row, index) => {
    const oldAutomaticName = `${oldPrefix}-disk-${index}`
    if (row.targetDiskName && row.targetDiskName !== oldAutomaticName) {
      return row
    }
    return Object.assign({}, row, { targetDiskName: `${newPrefix}-disk-${index}` })
  })
}

export function findActiveDrRun (runs = [], predicate = () => false) {
  return (runs || []).find(run => run && run.id && predicate(run)) || null
}

export function buildActiveDrRunQuery (planId) {
  return {
    planid: planId,
    page: 1,
    pagesize: 20
  }
}
